baseurl: "https://www.biocrafting.net"
languageCode: "de"
defaultLanguage: "de"
title: "www.biocrafting.net News"
publishdir: "/var/www/biocrafting/www.biocrafting.net/public/"
# theme: "greyshade"

author:
  name: "Biocrafting.net"
  email: "support@biocrafting.net"

params:
  description: "Die Newsseite f√ºr den Biocrafting-Teamspeak. Wenn du Fragen hast schick einfach eine E-Mail an support@biocrafting.net."

  subscribe_rss: "/index.xml"
  facebook_user: "biocraftingnet"
  twitter_user: "biocrafting"


# themeColor = "theme-base-09"
